import { Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Marquee from "@/components/Marquee";




const outfitFont = Outfit({
  
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${outfitFont.className} h-full antialiased`}
    >
    
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <Marquee/>
       
      {children}  </body>
      <Footer/>
    </html>
  );
}
